### PR TITLE
[OAP-1694][oap-native-sql][Scala] fix hash join w/ empty batch

### LINKED ISSUE #1694: [oap-native-sql] TPC-H q15 failed for ConditionedProbeArraysVisitorImpl MakeResultIterator does not support dependency type other than Batch
Error: Error running query: java.io.IOException: nativeFinishForIterator: finish failed with error msg Invalid: ConditionedProbeArraysVisitorImpl MakeResultIterator does not support dependency type other than Batch. (state=,code=0)

### PR DESCRIPTION
**Pull request by zhouyuan**
## What changes were proposed in this pull request?

This patch fixes the hash join w/ empty batch. 
fixes #1694 

Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>

## How was this patch tested?
locally verified with TPCH Q15

### CODE REVIEW

**Comment by xuechendi** [comment]
@zhouyuan , I think this fix may cause some logical error. I comment inline

File: oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala [hunk 1]
```diff
@@ -86,7 +86,7 @@ class ColumnarShuffledHashJoin(
         build_cb = null
       }
       build_cb = buildIter.next()
-      if (build_cb == null) {
+      if (build_cb.numRows == 0) {
         val res = new Iterator[ColumnarBatch] {
           override def hasNext: Boolean = {
             false
```
Comment (xuechendi) [inline oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala:92]: this iterator is used to indicate that this is the last iterator, and when numRows is 0, this only means one build_cb is empty

File: oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala [hunk 2]
```diff
@@ -128,9 +115,7 @@ class ColumnarShuffledHashJoin(
         projectedBuildKeyCols.foreach(v => v.close)
       }
     }
-    if (build_cb != null) {
-      build_cb = null
-    } else {
+    if (build_cb == null || htSize == 0) {
```
Comment (zhouyuan) [inline oap-native-sql/core/src/main/scala/com/intel/oap/expression/ColumnarShuffledHashJoin.scala:118]: @xuechendi modify the logic to work only when all batches are empty
