### PR TITLE
Set Minimum Sample Statistics Size

### LINKED ISSUE #525: Unit test "OAP accumulators on Parquet when hit index" in OapMetricsSuite fails randomly
This happens randomly
```
- get columns hit index
22:57:18.107 WARN org.apache.spark.sql.execution.datasources.oap.index.BPlusTreeScanner: OAP index is skipped. Disable OAP_EXECUTOR_INDEX_SELECTION to use index.
22:57:18.154 WARN org.apache.spark.sql.execution.datasources.oap.index.BPlusTreeScanner: OAP index is skipped. Disable OAP_EXECUTOR_INDEX_SELECTION to use index.
- skipped rows and selected rows *** FAILED ***
  1 did not equal 33 (FilterSuite.scala:962)
```
Full log at https://travis-ci.org/Intel-bigdata/OAP/builds/329340068?utm_source=github_status&utm_medium=notification

### PR DESCRIPTION
**Pull request by linhong-intel**
## What changes were proposed in this pull request?

Fixes #525 - MetricsSuite random failure issue.
Use a minimum sample size if data set is too small.

## How was this patch tested?

Unit test pass.
Without this PR 100 cycles stress test has 4 failures.
With this PR 100 cycles stress test has no failure.

### CODE REVIEW

**Comment by linhong-intel** [comment]
@LuciferYang @adrian-wang 
Please take a look.

File: src/main/scala/org/apache/spark/sql/execution/datasources/oap/statistics/SampleBasedStatistics.scala [hunk 1]
```diff
@@ -83,6 +83,8 @@ private[oap] class SampleBasedStatisticsWriter(schema: StructType, conf: Configu
 
   protected var sampleArray: Array[Key] = _
 
+  private val minSampleSize = 24
```
Comment (adrian-wang) [inline src/main/scala/org/apache/spark/sql/execution/datasources/oap/statistics/SampleBasedStatistics.scala]: leave this configurable?
