### PR TITLE
throw exception when indexing more than 2g rows

### LINKED ISSUE #448: Fail index building if count exceed limit
We only support row id < Int.MaxValue

### PR DESCRIPTION
**Pull request by xuyangit**
## What changes were proposed in this pull request?

Throw OapException when indexing more than 2g rows. Currently just check the recordCount in index record writer and if it exceeds Int.MaxValue, we throw an OapException.

## How was this patch tested?

Tested on tpcds1000 dataset with more than 2g rows for only one partition. 

Fixes #448

### CODE REVIEW

**Comment by linhong-intel** [comment]
is it possible to create a test case for this? I'm not sure if unit test have bear 2g rows (but it should).

File: src/main/scala/org/apache/spark/sql/execution/datasources/oap/index/BTreeIndexRecordWriter.scala [hunk 1]
```diff
@@ -52,6 +53,9 @@ private[index] case class BTreeIndexRecordWriter(
     val v = genericProjector(value).copy()
     multiHashMap.put(v, recordCount)
     statisticsManager.addOapKey(v)
+    if (recordCount == Int.MaxValue) {
```
Comment (chenghao-intel) [inline src/main/scala/org/apache/spark/sql/execution/datasources/oap/index/BTreeIndexRecordWriter.scala]: As we discussed previously, it will OOM even before we hit the maximize value, like 5M records. Can we have a hard code check for this? @yueawang

Comment (xuyangit) [reply src/main/scala/org/apache/spark/sql/execution/datasources/oap/index/BTreeIndexRecordWriter.scala]: @chenghao-intel ,currently i'm working on removing code which limits us from writing more than 2g rows. It can write successfully now but there is an issue with reading index. I'm trying to fix it now. 
So I think this check is appropriate but should be merged when the full test for 2g rows reading and writing is passed.
